name: tstokenlib
description: An implementation of the TSL1 Token Protocol for the BSV blockchain.
version: 0.1
repository: https://github.com/twostack/tstokenlib

environment:
  sdk: ^3.0.7

dependencies:

  dartsv: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
